### ISSUE TITLE
Base Image Build Fails on Arm64 With Error 137

### ISSUE THREAD

**Issue by keenanjohnson** [keenanjohnson/ros2_rust_workspace#21]
The Arm64 Base Image build has started failing for some reason. [You can see an example here.](https://github.com/keenanjohnson/ros2_rust_workspace/runs/6696344627?check_suite_focus=true)

The error happens trying to install cargo-ament-build and gives an exit code 137.

```
#19 [linux/arm64 7/7] RUN cargo install -vv cargo-ament-build
#19 1.003     Updating crates.io index
#19 242.6 Killed
#19 ERROR: process "/bin/sh -c cargo install -vv cargo-ament-build" did not complete successfully: exit code: 137
------
 > [linux/arm64 7/7] RUN cargo install -vv cargo-ament-build:
#19 1.003     Updating crates.io index
#19 242.6 Killed
------
Dockerfile:34
--------------------
  32 |     RUN pip install git+https://github.com/colcon/colcon-cargo.git git+https://github.com/colcon/colcon-ros-cargo.git
  33 |     # Install the cargo-ament-build plugin
  34 | >>> RUN cargo install -vv cargo-ament-build
  35 |     
--------------------
error: failed to solve: process "/bin/sh -c cargo install -vv cargo-ament-build" did not complete successfully: exit code: 137
Error: buildx failed with: error: failed to solve: process "/bin/sh -c cargo install -vv cargo-ament-build" did not complete successfully: exit code: 137
```

**Comment by keenanjohnson** [comment]
One interesting note is that the step of updating the crates.io index appears to be the step that runs out of memory ( if that is what is happening).

**Comment by keenanjohnson** [comment]
@nnmm if you are interested in following along :)

**Comment by mcandre** [comment]
Tried the sparse setting in my Cargo.toml file, same crashing behavior. When running in Docker, have to use the `--config net.git-fetch-with-cli=true` option as well (and have the git command line tool installed).
